apiVersion: apps/v1
kind: Deployment
metadata:
  name: books-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: books
  template:
    metadata:
      labels:
        app: books
    spec:
      containers:
      - name: books
        image: 038462752051.dkr.ecr.us-west-1.amazonaws.com/asg
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
# service type loadbalancer       
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: books
    k8s-app: books
  name: books
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 8080
  type: LoadBalancer
  selector:
    app: books
